# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 03:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20170224_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('enabled', 'Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('issue', 'Issue or Complaint'), ('denied', 'Denied'), ('disabled', 'Disabled')], default='submitted', max_length=36)),
                ('type', models.CharField(choices=[('url', 'url'), ('txt', 'Text'), ('social', 'Social Networking Handel'), ('other', 'Other')], default='text', max_length=36)),
                ('url', models.URLField(blank=True, default=None)),
                ('text', models.TextField(blank=True, max_length=640)),
                ('social', models.CharField(blank=True, max_length=36)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DurationField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=640)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='internshiptask',
            name='date_last_question_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshiptaskendanswers',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshiptaskanswer',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshiptaskprogress',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshiptaskprogress',
            name='progress',
            field=models.IntegerField(choices=[(0, '0-25%'), (25, '25%'), (37, '25-50%'), (50, '50%'), (62, '50-75%'), (75, '75%'), (87, '70-99%'), (100, '100% Complete')], default=50),
        ),
        migrations.AlterField(
            model_name='internshiptaskprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='app.InternshipTask'),
        ),
        migrations.AlterField(
            model_name='internshiptaskquestion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.InternshipTask'),
        ),
        migrations.AddField(
            model_name='taskfocus',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InternshipTask'),
        ),
    ]
