# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20170501_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DurationField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=640)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus', to='app.Internship')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipFocusEndAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(max_length=640)),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InternshipFocus')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskfocus',
            name='author',
        ),
        migrations.RemoveField(
            model_name='taskfocus',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskFocus',
        ),
    ]
