# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170606_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[(b'intern', b'Intern'), (b'internsuper', b'Organization Supervisor'), (b'counselor', b'Career / Guidance counselor'), (b'grove', b'Grove Employee')], default=b'Intern', max_length=36),
        ),
    ]
