# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180307_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='owning_org',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
