# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_member_owning_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='owning_org',
        ),
        migrations.AddField(
            model_name='orgunit',
            name='supervisor_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Member'),
        ),
    ]
