# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180307_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='supervisor_list',
        ),
        migrations.AddField(
            model_name='member',
            name='owning_org',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='app.OrgUnit'),
        ),
    ]
