# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180307_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='owning_org',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='app.OrgUnit'),
        ),
    ]
