# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180307_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='owning_org',
        ),
    ]
