# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_member_owning_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiptaskendanswers',
            name='description',
            field=models.TextField(default=b'Give task feedback here', max_length=640),
        ),
    ]
