# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-18 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_internshiptaskendanswers_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiptaskendanswers',
            name='description',
        ),
        migrations.AddField(
            model_name='internshiptaskendanswers',
            name='text',
            field=models.TextField(default=b'Type your feedback for the supervisor here.', max_length=640),
        ),
    ]
